### ISSUE TITLE
GPL-429 Add newly commisioned printer dnapbc2 (in AA312) for SM for 384 scalling

### ISSUE THREAD

**Issue by rl15** [sanger/print_my_barcode#49]
**User story**
GPL-429 | As Sample management rep (Adam F) we would like to add a newly commissioned Toshiba TEC thermal label printer (plate labels)  to support the shift to 384 process

**Who the primary contacts are for this story**
Adam F
Danni W

**Acceptance criteria**
To be considered successful the solution must allow:

1. Using existing plate label templates (see image)
2. Printer name dnapbc2 (in AA312) [https://172.17.97.17:631/printers/dnapbc2]
3. Adan would like to test from UAT environment first to align labels

**Additional context**

**Comment by rl15** [comment]
![IMG_20200428_135418](https://user-images.githubusercontent.com/7222395/80499199-94899180-8964-11ea-8b64-dc8d79709696.jpg)

**Comment by JamesGlover** [comment]
The printer will also need to be added to Sequencescape with a '384 Well Plate Double' printer type. This should be possible through the Admin page.

**Comment by jbeast** [comment]
Just checking PMB now, it already knows about a printer called `dnapbc2` in both UAT and production (perhaps there was a now decommissioned printer called this).

Hopefully this means once the printer has been added to Sequencescape it should work.

**Comment by rl15** [comment]
@JamesGlover  Who normally adds the printers? Us or operations?

**Comment by JamesGlover** [comment]
Either can, as agreed in stand up, I'll handle this one
Printer already seems to exist, dates from: 2014-09-19 09:22:53 but set up with 96 well templates. Switching to 384 double.

**Comment by JamesGlover** [comment]
Done
