### ISSUE TITLE
GPL-585 BUG - As sample management I can't print off quant barcodes

### ISSUE THREAD

**Issue by stevieing** [sanger/print_my_barcode#52]
**Describe the bug**
As sample management I can't print off quant barcodes

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page production quanthub
2. select printer
3. scan barcodes
4. click print
5. Nothing happens (CORS error)

**Expected behaviour**
Labels to be printed

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**
We need to fix the deployment of print my barcode to production and add CORS support for quanthub in production

**Comment by emrojo** [comment]
Pull request in internal git old-deployment
