### ISSUE TITLE
GPL-592 Move pmb into psd-deployment on UAT FCE

### ISSUE THREAD

**Issue by emrojo** [sanger/print_my_barcode#53]
**Description**
PMB is currently running in the old machines and the config changes need to be added manually. We would like to move the application into FCE and configure it to use the printers. 

**Who the primary contacts are for this work**
Andrew
Harriet
Eduardo

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by harrietc52** [comment]
There is a deploy print my barcode entry in psd-deployment. 
There is an archived branch on Luca's github repo for print_my_barcode called test_openstack. 
No host entry currently exists.

**Comment by harrietc52** [comment]
TODO:
[ ] -

**Comment by harrietc52** [comment]
Notes so far:
Provision: 
For workspace UAT only, ran terraform plan
branch: GPL-592-pmb-fce
Can now access: ssh -i sequencescape-test-keypair.pem ubuntu@172.27.84.19

Config
Created A name pmb-uat.psd.sanger.ac.uk by running dns_records.yml. Can now access: ssh pmb-uat.psd.sanger.ac.uk
Added monit and vim by running config_all.yml with limit pmb
Added filebeat, nginx by running psd_config.yml, which in turn runs config_sa_servers.yml
commented out mount_attached_volume task in config_sa_servers.yml as currently no volume is needed for PMB
full_upgrade is needed so apt update is called, before apt install filebeat
