### ISSUE TITLE
GPL-831-1 - As developers we need to create a v2 api

### ISSUE THREAD

**Issue by stevieing** [sanger/print_my_barcode#63]
**User story**
As developers we need to create a v2 api so we can route new print job requests

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] all requests and response should be json
- [ ] there should be a v2 endpoint for print job requests
- [ ] there should be a v2 api endpoint for printers

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
Do we need to also update the PMBClient too, for get printers and post print job, or maybe we don't need to use the client? Current post print job in the pmb client is for toshiba printers so accepts a label_template_id, and labels, wrapped in a body
