### ISSUE TITLE
GPL-831-5 - As developers we need to create configuration to store label templates

### ISSUE THREAD

**Issue by stevieing** [sanger/print_my_barcode#65]
**User story**
As developers we need to create configuration to store label templates

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] We should be able to create new label templates in a standard structure
- [ ] We should be able to use label templates to construct a print request
- [ ] The label templates should have same names as Toshiba label templates
- [ ] The templates should be human readable
- [ ] The templates should be stored in the deployment project (sprint role)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
Added the acceptance criteria to other story notes where might be useful.
