### ISSUE TITLE
GPL-831-4 - As developers we need to create some logic to construct a print request

### ISSUE THREAD

**Issue by stevieing** [sanger/print_my_barcode#66]
**User story**
The clear and concise user story describing what is required. e.g. As an SSR user I would like sample manifests to allow me to upload x ...

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] For Toshiba printers construct correct attributes and delegate to the existing printjob library
- [x] For Squix printers delegate to a new library for constructing sprint requests

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
Comments from -5: We should be able to use label templates to construct a print request. Dont think this is required as the label template name gets passed to the sprint client. the sprint client then handles the building of the request to SPrint

**Comment by harrietc52** [comment]
deployment branch GPL-813-4-sprint-to-pmb sprint_uri
