### ISSUE TITLE
GPL-935 BUG - Failure on re-creating list of printers in cups on startup (C=M, V=4)

### ISSUE THREAD

**Issue by emrojo** [sanger/print_my_barcode#77]
**Describe the bug**
Last startup of pmb failed on creating the list of printers in cups. Need to review why this happened:

This is the init log:
```
-> Running printers rake task
lpstat: Invalid argument
send: spawn id exp3 not open
    while executing
"send -- "$env(CUPSD_PASSWORD)\n""
    (file "/create-cups-printer.sh" line 5)
send: spawn id exp3 not open
    while executing
"send -- "$env(CUPSD_PASSWORD)\n""
    (file "/create-cups-printer.sh" line 5)
send: spawn id exp3 not open
    while executing
"send -- "$env(CUPSD_PASSWORD)\n""
    (file "/create-cups-printer.sh" line 5)
-> Printers rake task complete
Puma starting in single mode...
* Version 3.12.0 (ruby 2.6.6-p146), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
lpr: No such file or directory
lpr: No such file or directory
lpr: No such file or directory
lpr: No such file or directory
lpr: No such file or directory
```

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by BenTopping** [comment]
Line 5 of the shell script is: `send -- "$env(CUPSD_PASSWORD)\n"`
I would suspect the instance the script was running on did not have the CUPSD_PASSWORD environmental variable set and it could not find it so error'd. Need to find where CUPSD_PASSWORD is being set and make sure it is set before the script is run.
Should also probably be wrapping the `send` in a try/or statement.

**Comment by sdjmchattie** [comment]
I logged into `pmb-uat` and ran `docker restart` on the print my barcode container and I saw only one error message when it was restarting `mkdir: cannot create directory ‘/etc/cups/’: File exists` which I think is fine.  I would say this looks fixed, but I didn't see it broken.

**Comment by BenTopping** [comment]
SUSPECTED issue: running the script deploy_samples_extraction.yml in the deployment project also deployed / affected PMB since they are in the same stack, potentially it deployed PMB without the CUPS password which caused the error?

**Comment by BenTopping** [comment]
Another possible cause is that docker start-up order. PMB depends on the cupsd instance to be available for the command to execute correctly, so if its not available (PMB container spins up before the cupsd one) it could cause an error like this
