### ISSUE TITLE
DPL-300 [BUG] - When we print labels off from Limber the NT number is missing a digit on the small label that goes on the top of the tube (C=S, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/print_my_barcode#98]
**Describe the bug**
Hoping you can help us - we've got an issue with a particular tube label printer G216bc. When we print labels off from Limber the NT number is missing a digit on the small label that goes on the top of the tube. The text is centrally aligned so we don't think it is a physical issue with the printer's label alignment, and the digit is not missing when the same label is printed from sequencescape, so I have my suspicions it is a PSD issue. I may be misdirected in this so please let me know what you think!

This issue affects the sequencing team particularly as they have to search for tubes in their freezer inbox by their top label number.

**RT Ticket Number**
743880

**Screenshots**
If applicable, 
![IMG_1757](https://user-images.githubusercontent.com/519327/154929510-271c8180-f8ed-4c51-82bc-8f1e62cb9db8.jpg)
add screenshots to help explain your problem.

**Comment by KatyTaylor** [comment]
I asked Michael if this was still an issue and he confirmed today:

> Yes, just had another go and we still have a missing digit on this printer when printing from Limber (image attached).

![F794D188-3F81-47F5-BC4E-AC5B65827C5E](https://user-images.githubusercontent.com/10407809/161530233-a128b552-a4e5-4d16-a612-daa13d25a7dd.jpeg)

**Comment by KatyTaylor** [comment]
**Update:** 

I raised a ticket yesterday (Mon 4th April) with the service desk (Carl) to look into this printer - since it works on one printer but not the other it seems like it could be a physical alignment issue. Request number is 329787.

**Comment by stevieing** [comment]
closed in favour of sanger/general-backlog-items#189
